**II. Formulation of the Problem of Generating Combinatorial Objects**

In most of the generation problems, we have:

Each object (can be?) is represented by an array X[1:N]

The elements of the array are taken from a domain S={a1,a2,...,am}. Often, S is a finite set of successive integers.

The values of array X must satisfy some constraints C so that X represents a legitimate object of the type in question.

We will show the specifics in each of the following instances of combinatorial object generation

**Problem 3: Generation of all directed graphs of n nodes**

* Every digraph of n nodes is representable by a 2D array A[1:n,1:n], which is the well-known adjacency matrix.
* The values of the entries in the array are binary and also are independent of one another.
* The 2D array can be represented by a a 1D binary array X[1:N] where N=n2
* The value of each X[i] is in {0,1}
* The constraints C are empty because the values of entries of X (which are the entries of A) are independent
* Mapping from A to X: Stack the rows of A one after another. Thus, X[(i-1)n + j] = A[i,j]

In [4]:
# edges are independent of each other. having an edge from i to j in a graph has 
# no dependency on another edge.
# So the constraint set for this problem is empty and Bound always return true. 

def Bound(X,r):     
    return True     

In [5]:
def getNext(X,r):
    X[r]=X[r]+1
    while X[r] <=1:            #while X[r] is in domian. here the possible values are 0 and 1
        if Bound(X,r)==True :
            return
        else:
            X[r]=X[r] +1 
    
    X[r]=a0
    

In [6]:
#Backtracking
import networkx as nx
import numpy
import matplotlib.pyplot as plt
%matplotlib inline 


r=0          # r is the tree level, or index of X. 
X=[]         # X represent one instance of the permutable object 
a0=-1        # this is an initial value for elements of X. pick something that tells
             #       this element has not been assigned yet
N = int(raw_input("Enter N , the total number of nodes: "))   # Size of the array. change based on your problem    
count =0

for i in range(0,(N**2)):                #creating X[1:N^2]   Index starts from 0 equivalant to range(0,N**2)
    X.append(a0)
    

print "The initial state of X is : " + str(X)
    
while r>-1:
    getNext(X,r)
    if (X[r]==a0):
        r=r-1
    elif r==N**2-1:
        print "found a solution: "
        count +=1
        a = numpy.array(X)
        a=a.reshape(N,N)
        print a
        #G=nx.MultiDiGraph(a)
        #nx.draw(G,nodecolor='r',edge_color='b',with_labels=True)
        #plt.show()
    else:
        r=r+1
    
print count

Enter N , the total number of nodes: 3
The initial state of X is : [-1, -1, -1, -1, -1, -1, -1, -1, -1]
found a solution: 
[[0 0 0]
 [0 0 0]
 [0 0 0]]
found a solution: 
[[0 0 0]
 [0 0 0]
 [0 0 1]]
found a solution: 
[[0 0 0]
 [0 0 0]
 [0 1 0]]
found a solution: 
[[0 0 0]
 [0 0 0]
 [0 1 1]]
found a solution: 
[[0 0 0]
 [0 0 0]
 [1 0 0]]
found a solution: 
[[0 0 0]
 [0 0 0]
 [1 0 1]]
found a solution: 
[[0 0 0]
 [0 0 0]
 [1 1 0]]
found a solution: 
[[0 0 0]
 [0 0 0]
 [1 1 1]]
found a solution: 
[[0 0 0]
 [0 0 1]
 [0 0 0]]
found a solution: 
[[0 0 0]
 [0 0 1]
 [0 0 1]]
found a solution: 
[[0 0 0]
 [0 0 1]
 [0 1 0]]
found a solution: 
[[0 0 0]
 [0 0 1]
 [0 1 1]]
found a solution: 
[[0 0 0]
 [0 0 1]
 [1 0 0]]
found a solution: 
[[0 0 0]
 [0 0 1]
 [1 0 1]]
found a solution: 
[[0 0 0]
 [0 0 1]
 [1 1 0]]
found a solution: 
[[0 0 0]
 [0 0 1]
 [1 1 1]]
found a solution: 
[[0 0 0]
 [0 1 0]
 [0 0 0]]
found a solution: 
[[0 0 0]
 [0 1 0]
 [0 0 1]]
found a solution: 
[[0 0 0]
 [0 1 0]
 [0 1 0]]
fou